# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_skill.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_skill.proto',
  package='msg_skill',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fmsg_skill.proto\x12\tmsg_skill\"\x81\x01\n\x16skill_items_attributes\x12\x0c\n\x04type\x18\x01 \x01(\x07\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08use_type\x18\x03 \x01(\x07\x12\x18\n\x10time_of_duration\x18\x04 \x01(\x07\x12\x1e\n\x16start_time_of_duration\x18\x05 \x01(\x07\"4\n\x0bskill_items\x12\r\n\x05level\x18\x01 \x01(\x07\x12\x16\n\x0epractice_value\x18\x02 \x01(\x07\"\xb1\x01\n\nskill_info\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x62ook_id\x18\x03 \x01(\x07\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x18\n\x10\x61ssociated_forms\x18\x05 \x01(\t\x12\x12\n\nconsume_mp\x18\x06 \x01(\x07\x12\x13\n\x0bproficiency\x18\x07 \x01(\x07\x12%\n\x05items\x18\n \x03(\x0b\x32\x16.msg_skill.skill_itemsb\x06proto3')
)




_SKILL_ITEMS_ATTRIBUTES = _descriptor.Descriptor(
  name='skill_items_attributes',
  full_name='msg_skill.skill_items_attributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='msg_skill.skill_items_attributes.type', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='msg_skill.skill_items_attributes.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_type', full_name='msg_skill.skill_items_attributes.use_type', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_of_duration', full_name='msg_skill.skill_items_attributes.time_of_duration', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time_of_duration', full_name='msg_skill.skill_items_attributes.start_time_of_duration', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=160,
)


_SKILL_ITEMS = _descriptor.Descriptor(
  name='skill_items',
  full_name='msg_skill.skill_items',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='msg_skill.skill_items.level', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='practice_value', full_name='msg_skill.skill_items.practice_value', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=214,
)


_SKILL_INFO = _descriptor.Descriptor(
  name='skill_info',
  full_name='msg_skill.skill_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='msg_skill.skill_info.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='msg_skill.skill_info.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='book_id', full_name='msg_skill.skill_info.book_id', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='msg_skill.skill_info.reason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='associated_forms', full_name='msg_skill.skill_info.associated_forms', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consume_mp', full_name='msg_skill.skill_info.consume_mp', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proficiency', full_name='msg_skill.skill_info.proficiency', index=6,
      number=7, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='msg_skill.skill_info.items', index=7,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=394,
)

_SKILL_INFO.fields_by_name['items'].message_type = _SKILL_ITEMS
DESCRIPTOR.message_types_by_name['skill_items_attributes'] = _SKILL_ITEMS_ATTRIBUTES
DESCRIPTOR.message_types_by_name['skill_items'] = _SKILL_ITEMS
DESCRIPTOR.message_types_by_name['skill_info'] = _SKILL_INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

skill_items_attributes = _reflection.GeneratedProtocolMessageType('skill_items_attributes', (_message.Message,), dict(
  DESCRIPTOR = _SKILL_ITEMS_ATTRIBUTES,
  __module__ = 'msg_skill_pb2'
  # @@protoc_insertion_point(class_scope:msg_skill.skill_items_attributes)
  ))
_sym_db.RegisterMessage(skill_items_attributes)

skill_items = _reflection.GeneratedProtocolMessageType('skill_items', (_message.Message,), dict(
  DESCRIPTOR = _SKILL_ITEMS,
  __module__ = 'msg_skill_pb2'
  # @@protoc_insertion_point(class_scope:msg_skill.skill_items)
  ))
_sym_db.RegisterMessage(skill_items)

skill_info = _reflection.GeneratedProtocolMessageType('skill_info', (_message.Message,), dict(
  DESCRIPTOR = _SKILL_INFO,
  __module__ = 'msg_skill_pb2'
  # @@protoc_insertion_point(class_scope:msg_skill.skill_info)
  ))
_sym_db.RegisterMessage(skill_info)


# @@protoc_insertion_point(module_scope)
