# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_npc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import im.common.proto.msg_role_pb2 as msg__role__pb2
try:
  msg__equipment__pb2 = msg__role__pb2.msg__equipment__pb2
except AttributeError:
  msg__equipment__pb2 = msg__role__pb2.msg_equipment_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_npc.proto',
  package='msg_npc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmsg_npc.proto\x12\x07msg_npc\x1a\x0emsg_role.proto\"R\n\x0bnpc_ability\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x07\x12\x13\n\x0bresult_type\x18\x03 \x01(\x07\x12\x11\n\tresult_id\x18\x04 \x01(\x07\"\xdf\x01\n\x0bnpc_details\x12\n\n\x02id\x18\x01 \x01(\x07\x12\x10\n\x08npc_code\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05tiles\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\x07\x12\r\n\x05level\x18\x06 \x01(\x07\x12%\n\x07\x61\x62ility\x18\x07 \x03(\x0b\x32\x14.msg_npc.npc_ability\x12$\n\x08\x62\x61\x63kpack\x18\x08 \x03(\x0b\x32\x12.msg_role.backpack\x12+\n\x0croleDeatails\x18\t \x01(\x0b\x32\x15.msg_role.roleDetails\"1\n\x08npc_list\x12%\n\x07\x64\x65tails\x18\x01 \x03(\x0b\x32\x14.msg_npc.npc_detailsb\x06proto3')
  ,
  dependencies=[msg__role__pb2.DESCRIPTOR,])




_NPC_ABILITY = _descriptor.Descriptor(
  name='npc_ability',
  full_name='msg_npc.npc_ability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='msg_npc.npc_ability.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='msg_npc.npc_ability.value', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_type', full_name='msg_npc.npc_ability.result_type', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_id', full_name='msg_npc.npc_ability.result_id', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=124,
)


_NPC_DETAILS = _descriptor.Descriptor(
  name='npc_details',
  full_name='msg_npc.npc_details',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='msg_npc.npc_details.id', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='npc_code', full_name='msg_npc.npc_details.npc_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='msg_npc.npc_details.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tiles', full_name='msg_npc.npc_details.tiles', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='msg_npc.npc_details.type', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='msg_npc.npc_details.level', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ability', full_name='msg_npc.npc_details.ability', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backpack', full_name='msg_npc.npc_details.backpack', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roleDeatails', full_name='msg_npc.npc_details.roleDeatails', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=350,
)


_NPC_LIST = _descriptor.Descriptor(
  name='npc_list',
  full_name='msg_npc.npc_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='details', full_name='msg_npc.npc_list.details', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=401,
)

_NPC_DETAILS.fields_by_name['ability'].message_type = _NPC_ABILITY
_NPC_DETAILS.fields_by_name['backpack'].message_type = msg__role__pb2._BACKPACK
_NPC_DETAILS.fields_by_name['roleDeatails'].message_type = msg__role__pb2._ROLEDETAILS
_NPC_LIST.fields_by_name['details'].message_type = _NPC_DETAILS
DESCRIPTOR.message_types_by_name['npc_ability'] = _NPC_ABILITY
DESCRIPTOR.message_types_by_name['npc_details'] = _NPC_DETAILS
DESCRIPTOR.message_types_by_name['npc_list'] = _NPC_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

npc_ability = _reflection.GeneratedProtocolMessageType('npc_ability', (_message.Message,), dict(
  DESCRIPTOR = _NPC_ABILITY,
  __module__ = 'msg_npc_pb2'
  # @@protoc_insertion_point(class_scope:msg_npc.npc_ability)
  ))
_sym_db.RegisterMessage(npc_ability)

npc_details = _reflection.GeneratedProtocolMessageType('npc_details', (_message.Message,), dict(
  DESCRIPTOR = _NPC_DETAILS,
  __module__ = 'msg_npc_pb2'
  # @@protoc_insertion_point(class_scope:msg_npc.npc_details)
  ))
_sym_db.RegisterMessage(npc_details)

npc_list = _reflection.GeneratedProtocolMessageType('npc_list', (_message.Message,), dict(
  DESCRIPTOR = _NPC_LIST,
  __module__ = 'msg_npc_pb2'
  # @@protoc_insertion_point(class_scope:msg_npc.npc_list)
  ))
_sym_db.RegisterMessage(npc_list)


# @@protoc_insertion_point(module_scope)
