# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_book.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import im.common.proto.msg_skill_pb2 as msg__skill__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_book.proto',
  package='msg_book',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0emsg_book.proto\x12\x08msg_book\x1a\x0fmsg_skill.proto\"P\n\x12\x62ook_related_skill\x12)\n\nskill_list\x18\x01 \x03(\x0b\x32\x15.msg_skill.skill_info\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x07\" \n\x0f\x62ook_level_info\x12\r\n\x05level\x18\x01 \x01(\x07\"\xf3\x01\n\x0c\x62ook_details\x12\n\n\x02id\x18\x01 \x01(\x07\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07reasion\x18\x03 \x01(\t\x12\x0f\n\x07\x64urable\x18\x04 \x01(\x07\x12\x0c\n\x04type\x18\x05 \x01(\x07\x12\r\n\x05price\x18\x06 \x01(\x07\x12\x0e\n\x06weight\x18\x07 \x01(\t\x12\x16\n\x0e\x61ttainments_up\x18\x08 \x01(\x07\x12-\n\nlevel_info\x18\n \x03(\x0b\x32\x19.msg_book.book_level_info\x12\x33\n\rrelated_skill\x18\x0b \x03(\x0b\x32\x1c.msg_book.book_related_skill\"4\n\tbook_list\x12\'\n\x07\x64\x65tails\x18\x01 \x03(\x0b\x32\x16.msg_book.book_detailsb\x06proto3')
  ,
  dependencies=[msg__skill__pb2.DESCRIPTOR,])




_BOOK_RELATED_SKILL = _descriptor.Descriptor(
  name='book_related_skill',
  full_name='msg_book.book_related_skill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skill_list', full_name='msg_book.book_related_skill.skill_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='msg_book.book_related_skill.content', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=125,
)


_BOOK_LEVEL_INFO = _descriptor.Descriptor(
  name='book_level_info',
  full_name='msg_book.book_level_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='msg_book.book_level_info.level', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=159,
)


_BOOK_DETAILS = _descriptor.Descriptor(
  name='book_details',
  full_name='msg_book.book_details',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='msg_book.book_details.id', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='msg_book.book_details.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reasion', full_name='msg_book.book_details.reasion', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='durable', full_name='msg_book.book_details.durable', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='msg_book.book_details.type', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='msg_book.book_details.price', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='msg_book.book_details.weight', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attainments_up', full_name='msg_book.book_details.attainments_up', index=7,
      number=8, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level_info', full_name='msg_book.book_details.level_info', index=8,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='related_skill', full_name='msg_book.book_details.related_skill', index=9,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=405,
)


_BOOK_LIST = _descriptor.Descriptor(
  name='book_list',
  full_name='msg_book.book_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='details', full_name='msg_book.book_list.details', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=459,
)

_BOOK_RELATED_SKILL.fields_by_name['skill_list'].message_type = msg__skill__pb2._SKILL_INFO
_BOOK_DETAILS.fields_by_name['level_info'].message_type = _BOOK_LEVEL_INFO
_BOOK_DETAILS.fields_by_name['related_skill'].message_type = _BOOK_RELATED_SKILL
_BOOK_LIST.fields_by_name['details'].message_type = _BOOK_DETAILS
DESCRIPTOR.message_types_by_name['book_related_skill'] = _BOOK_RELATED_SKILL
DESCRIPTOR.message_types_by_name['book_level_info'] = _BOOK_LEVEL_INFO
DESCRIPTOR.message_types_by_name['book_details'] = _BOOK_DETAILS
DESCRIPTOR.message_types_by_name['book_list'] = _BOOK_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

book_related_skill = _reflection.GeneratedProtocolMessageType('book_related_skill', (_message.Message,), dict(
  DESCRIPTOR = _BOOK_RELATED_SKILL,
  __module__ = 'msg_book_pb2'
  # @@protoc_insertion_point(class_scope:msg_book.book_related_skill)
  ))
_sym_db.RegisterMessage(book_related_skill)

book_level_info = _reflection.GeneratedProtocolMessageType('book_level_info', (_message.Message,), dict(
  DESCRIPTOR = _BOOK_LEVEL_INFO,
  __module__ = 'msg_book_pb2'
  # @@protoc_insertion_point(class_scope:msg_book.book_level_info)
  ))
_sym_db.RegisterMessage(book_level_info)

book_details = _reflection.GeneratedProtocolMessageType('book_details', (_message.Message,), dict(
  DESCRIPTOR = _BOOK_DETAILS,
  __module__ = 'msg_book_pb2'
  # @@protoc_insertion_point(class_scope:msg_book.book_details)
  ))
_sym_db.RegisterMessage(book_details)

book_list = _reflection.GeneratedProtocolMessageType('book_list', (_message.Message,), dict(
  DESCRIPTOR = _BOOK_LIST,
  __module__ = 'msg_book_pb2'
  # @@protoc_insertion_point(class_scope:msg_book.book_list)
  ))
_sym_db.RegisterMessage(book_list)


# @@protoc_insertion_point(module_scope)
