# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_equipment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_equipment.proto',
  package='msg_equipment',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13msg_equipment.proto\x12\rmsg_equipment\"I\n\x06\x65\x66\x66\x65\x63t\x12\r\n\x05Lidao\x18\x01 \x01(\x07\x12\x10\n\x08Jingmiao\x18\x02 \x01(\x07\x12\x0e\n\x06\x66\x61ngyu\x18\x03 \x01(\x07\x12\x0e\n\x06gongji\x18\x04 \x01(\x07\";\n\x0brequirement\x12\x0e\n\x06Jianfa\x18\x01 \x01(\x07\x12\r\n\x05\x44\x61ofa\x18\x02 \x01(\x07\x12\r\n\x05Lidao\x18\x03 \x01(\x07\"\xf7\x02\n\tattribute\x12\x0c\n\x04rank\x18\x01 \x01(\x07\x12\x10\n\x08quiality\x18\x02 \x01(\x07\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\x07\x12\x0c\n\x04part\x18\x05 \x01(\x07\x12\x10\n\x08metarial\x18\x06 \x01(\x07\x12\x0c\n\x04tips\x18\x07 \x01(\x07\x12\x0c\n\x04icon\x18\x08 \x01(\t\x12\x0f\n\x07\x64urable\x18\t \x01(\x07\x12\x0e\n\x06weight\x18\n \x01(\x07\x12\x0e\n\x06\x61ttack\x18\x0b \x01(\x07\x12\x0f\n\x07\x64\x65\x66\x65nce\x18\x0c \x01(\x07\x12\x13\n\x0b\x63ombination\x18\r \x03(\x07\x12&\n\x07\x65\x66\x66\x65\x63ts\x18\x0e \x03(\x0b\x32\x15.msg_equipment.effect\x12\x30\n\x0crequirements\x18\x0f \x03(\x0b\x32\x1a.msg_equipment.requirement\x12\x0f\n\x07\x65xplain\x18\x10 \x01(\t\x12\x10\n\x08skill_id\x18\x11 \x01(\x07\x12\x0f\n\x07\x62inding\x18\x12 \x01(\x08\x12\r\n\x05price\x18\x13 \x01(\x11\x62\x06proto3')
)




_EFFECT = _descriptor.Descriptor(
  name='effect',
  full_name='msg_equipment.effect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Lidao', full_name='msg_equipment.effect.Lidao', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Jingmiao', full_name='msg_equipment.effect.Jingmiao', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fangyu', full_name='msg_equipment.effect.fangyu', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gongji', full_name='msg_equipment.effect.gongji', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=111,
)


_REQUIREMENT = _descriptor.Descriptor(
  name='requirement',
  full_name='msg_equipment.requirement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Jianfa', full_name='msg_equipment.requirement.Jianfa', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Daofa', full_name='msg_equipment.requirement.Daofa', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Lidao', full_name='msg_equipment.requirement.Lidao', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=172,
)


_ATTRIBUTE = _descriptor.Descriptor(
  name='attribute',
  full_name='msg_equipment.attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rank', full_name='msg_equipment.attribute.rank', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quiality', full_name='msg_equipment.attribute.quiality', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='msg_equipment.attribute.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='msg_equipment.attribute.type', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='part', full_name='msg_equipment.attribute.part', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metarial', full_name='msg_equipment.attribute.metarial', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tips', full_name='msg_equipment.attribute.tips', index=6,
      number=7, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon', full_name='msg_equipment.attribute.icon', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='durable', full_name='msg_equipment.attribute.durable', index=8,
      number=9, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='msg_equipment.attribute.weight', index=9,
      number=10, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attack', full_name='msg_equipment.attribute.attack', index=10,
      number=11, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='defence', full_name='msg_equipment.attribute.defence', index=11,
      number=12, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='combination', full_name='msg_equipment.attribute.combination', index=12,
      number=13, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='effects', full_name='msg_equipment.attribute.effects', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requirements', full_name='msg_equipment.attribute.requirements', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='explain', full_name='msg_equipment.attribute.explain', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_id', full_name='msg_equipment.attribute.skill_id', index=16,
      number=17, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='binding', full_name='msg_equipment.attribute.binding', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='msg_equipment.attribute.price', index=18,
      number=19, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=550,
)

_ATTRIBUTE.fields_by_name['effects'].message_type = _EFFECT
_ATTRIBUTE.fields_by_name['requirements'].message_type = _REQUIREMENT
DESCRIPTOR.message_types_by_name['effect'] = _EFFECT
DESCRIPTOR.message_types_by_name['requirement'] = _REQUIREMENT
DESCRIPTOR.message_types_by_name['attribute'] = _ATTRIBUTE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

effect = _reflection.GeneratedProtocolMessageType('effect', (_message.Message,), dict(
  DESCRIPTOR = _EFFECT,
  __module__ = 'msg_equipment_pb2'
  # @@protoc_insertion_point(class_scope:msg_equipment.effect)
  ))
_sym_db.RegisterMessage(effect)

requirement = _reflection.GeneratedProtocolMessageType('requirement', (_message.Message,), dict(
  DESCRIPTOR = _REQUIREMENT,
  __module__ = 'msg_equipment_pb2'
  # @@protoc_insertion_point(class_scope:msg_equipment.requirement)
  ))
_sym_db.RegisterMessage(requirement)

attribute = _reflection.GeneratedProtocolMessageType('attribute', (_message.Message,), dict(
  DESCRIPTOR = _ATTRIBUTE,
  __module__ = 'msg_equipment_pb2'
  # @@protoc_insertion_point(class_scope:msg_equipment.attribute)
  ))
_sym_db.RegisterMessage(attribute)


# @@protoc_insertion_point(module_scope)
