# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_event.proto',
  package='msg_event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fmsg_event.proto\x12\tmsg_event\"\x8c\x01\n\revent_details\x12\n\n\x02id\x18\x01 \x01(\x07\x12\x0e\n\x06npc_id\x18\x02 \x01(\x07\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\x07\x12\r\n\x05value\x18\x05 \x01(\x07\x12\x0f\n\x07reasion\x18\x06 \x01(\t\x12\x12\n\nevent_type\x18\x07 \x01(\x07\x12\x0f\n\x07\x61rea_id\x18\x08 \x01(\x07\"7\n\nevent_list\x12)\n\x07\x64\x65tails\x18\x01 \x03(\x0b\x32\x18.msg_event.event_detailsb\x06proto3')
)




_EVENT_DETAILS = _descriptor.Descriptor(
  name='event_details',
  full_name='msg_event.event_details',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='msg_event.event_details.id', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='npc_id', full_name='msg_event.event_details.npc_id', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='msg_event.event_details.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='msg_event.event_details.type', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='msg_event.event_details.value', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reasion', full_name='msg_event.event_details.reasion', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='msg_event.event_details.event_type', index=6,
      number=7, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='area_id', full_name='msg_event.event_details.area_id', index=7,
      number=8, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=171,
)


_EVENT_LIST = _descriptor.Descriptor(
  name='event_list',
  full_name='msg_event.event_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='details', full_name='msg_event.event_list.details', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=228,
)

_EVENT_LIST.fields_by_name['details'].message_type = _EVENT_DETAILS
DESCRIPTOR.message_types_by_name['event_details'] = _EVENT_DETAILS
DESCRIPTOR.message_types_by_name['event_list'] = _EVENT_LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

event_details = _reflection.GeneratedProtocolMessageType('event_details', (_message.Message,), dict(
  DESCRIPTOR = _EVENT_DETAILS,
  __module__ = 'msg_event_pb2'
  # @@protoc_insertion_point(class_scope:msg_event.event_details)
  ))
_sym_db.RegisterMessage(event_details)

event_list = _reflection.GeneratedProtocolMessageType('event_list', (_message.Message,), dict(
  DESCRIPTOR = _EVENT_LIST,
  __module__ = 'msg_event_pb2'
  # @@protoc_insertion_point(class_scope:msg_event.event_list)
  ))
_sym_db.RegisterMessage(event_list)


# @@protoc_insertion_point(module_scope)
